### ISSUE TITLE
Visual Resources are Color Coded 

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1047]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to differentiate easily the resource types that are in graph.

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We will follow Fiori NEXT Guidelines when comes to the style of the resource box

**Tasks**

- [ ] Make sure the colors don't interfere with https://github.com/kyma-project/busola/issues/1043

![image](https://user-images.githubusercontent.com/478866/156552706-97723b71-0a65-4a53-b36e-13a006c96672.png)
![image](https://user-images.githubusercontent.com/478866/156552998-138584dc-f59d-48f0-9417-a481a251120b.png)
![image](https://user-images.githubusercontent.com/478866/156577312-d1e2eb9a-8469-4e6a-8961-cc1a5d0efba6.png)
