### ISSUE TITLE
Visual Resources for Storage Objects 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1048]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to see in a visual way the connections for our Storage Objects.

**Acceptance Criteria**

- [ ] Follow Project DOD
- [x] We will follow Fiori Guidelines when comes to the style of the resource boxes
- [x] We will follow just 1 level of dependency
- [x] We Cover Secrets, ConfigMaps,PVC, PV 
- [x] The Styling is done in a separate task

**Tasks**

- [ ] 

**Inspiration**

- [Storage Objects](https://shipit.dev/posts/kubernetes-overview-diagrams.html#storage)

![image](https://user-images.githubusercontent.com/478866/156554023-fb19f53b-cc43-4578-99d2-c79c3c04bc9c.png)
