### ISSUE TITLE
Visual Resources for RBAC Objects

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1049]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to see a visual representation of RBAC Objects.

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We will follow Fiori Guidelines when comes to the style of the resource boxes
- [ ] We will follow just 1 level of dependency
- [ ] We cover Role, Role Binding, ServiceAccounts
- [ ] we cover styling in another story

**Tasks**

- [ ] 

**Inspiration**

- [RBAC Objects](https://shipit.dev/posts/kubernetes-overview-diagrams.html#rbac)

![image](https://user-images.githubusercontent.com/478866/156554023-fb19f53b-cc43-4578-99d2-c79c3c04bc9c.png)
