### ISSUE TITLE
Visual Resources for Workload Objects

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1051]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to see a visual representation of Workload Objects.

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We will follow Fiori Guidelines when comes to the style of the resource boxes
- [ ] We will follow all the level of nesting, from Ingress to Config Map
- [ ] We target Deployment, ReplicaSet, StatefulSet, DeamonSet,CronJob,Job, Pod, HPA
- [ ] the styling is done in another task

**Tasks**

- [ ] 

**Inspiration**

- [workload Objects](https://shipit.dev/posts/kubernetes-overview-diagrams.html#workload)

![image](https://user-images.githubusercontent.com/478866/156561161-ba53c991-9779-4b13-9a41-6ade8a2085e4.png)
