### ISSUE TITLE
Visual Resources for Networking Objects

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1052]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to see a visual representation of Networking Objects.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We will follow Fiori Guidelines when comes to the style of the resource boxes
- [x] We will follow all the level of nesting, from Ingress to Config Map
- [x] This includes, Services, Ingress, Virtual Services, API Rules, Gateways
- [x] the styling is done in a separate task

**Tasks**

- [ ] 

**Inspiration**

- [Network Objects](https://shipit.dev/posts/kubernetes-overview-diagrams.html#networking)

![image](https://user-images.githubusercontent.com/478866/156561161-ba53c991-9779-4b13-9a41-6ade8a2085e4.png)

**Comment by valentinvieriu** [comment]
This is not implemented as requested.
