### ISSUE TITLE
Have Card Detail for Visual Resource

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1057]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to interact with the elements in the Visual Resource, and see detail about them and get a deep link.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We will follow Fiori Guidelines when comes to the style of the resource boxes
- [x] The card shows some basic details, and offers deep linking
- [x] the position is similar with the one in the example

**Tasks**

- [ ] 

**Inspiration**

- [Network Objects](https://shipit.dev/posts/kubernetes-overview-diagrams.html#networking)

![image](https://user-images.githubusercontent.com/478866/156574901-a6acd9c9-8cd3-45c6-b9f0-f1345a6312e2.png)
