### ISSUE TITLE
Align Command Palette aliases to k9s aliases 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1110]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able use the same shortcuts as K9s application.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We align our shortcuts to follow the k9s aliases
- [x] We have a dynamic way of updating our aliases depending on the resources running in the cluster (CR can be accessed by their name )
- [x] Tests are present testing the functionality
- [x] Handle commands for navigation to custom resource list (e.g. cluster/shoot--kyma-prow--nkyma/customresources/clusteraddonsconfigurations.addons.kyma-project.io) and custom resource details (/cluster/shoot--kyma-prow--nkyma/customresources/compassconnections.compass.kyma-project.io/a)
- [x] 2 actions for Namespace - switch as a default and go to overview

**Tasks**

**Attachments**

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/478866/159113609-45f47ed2-2849-414b-8026-d9f961cd15ab.png">
<img width="785" alt="image" src="https://user-images.githubusercontent.com/478866/159113619-37a337d2-4b1a-46e1-95c4-77b0203cd606.png">

**Comment by Wawrzyn321** [comment]
Related #1212, but it won't close this issue.
