### ISSUE TITLE
See Prometheus Resource Graphs at Deployment Level

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1114]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able see Prometheus Resource Graphs at Deployment Level .

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We display similar graphs as Cluster Overview ( CPU, Memory, Network ) but targeted to Deployment
- [x] Stretch Goal - use stack graph to divide resources by container

**Tasks**
