### ISSUE TITLE
CRDs should be visible at Cluster Level Only 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1115]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would expect that I see all CRDs at cluster level ( cluster bound and namespace bound ).

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] All CRDs are visible at Cluster level only.
- [x] Namespace CRD will display a complete list of all instances, specifying the namespace, and deep linking to the namespace
- [x] At Namespace level we display Custom Resources only, the list is cluster by group and the detail page just lists the instances with deep link to instance detail page.
- [x] Display Custom Resources on Cluster level, too.
- [x] Tests are present testing the functionality

**Tasks**
