### ISSUE TITLE
Allow Upload of Multiple YAML files

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1130]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to upload more than 1 file to deploy my app. I expect those files to be concatenated and applied to my cluster

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] The user can upload 1 or many files
- [ ] After upload, the files are concatenated, and presented to the user as 1 YAML file

**Tasks**
