### ISSUE TITLE
Allow the user to upload YAML files at Namespace level

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1131]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to upload my app as 1 YAML file or more YAML files to deploy my app at namespace level.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] The user can upload 1 or many files
- [x] After upload, the files are concatenated, and presented to the user as 1 YAML file
- [x] all the resources will be namespaces to the current namespace
- [x] if one of the resources has a different namespace provided, this will be marked as a warning to the user. He will be allowed to push the changes
- [x] ~if one of the resources is cluster wide, he will get an warning but he will be allowed to push the changes~
**Tasks**
