### ISSUE TITLE
Busola can be extended to support custom views for custom CRDs

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1232]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to extend Busola by configuration. I would expect that with a small configuration I can enable a custom UI in Busola where I can List, View Detail, and Edit and Delete a component

**Acceptance Criteria**

- [x] The component can have a configurable menu item that can be cluster level or namespace level
- [x] The component can have a configurable list where columns can be picked up and have at least 3 components
- [x] The Component can have configurable detail page and we will provide at least 3 components and we can choose 2 layout types ( stacked and 2 columns )
- [x] The Component can have a configurable Create Page with Simple and Advanced sections
- [x] The Component can support multiple translations and multiple languages
- [ ] The configuration is versioned
- [ ] The configuration is clearly documented with examples - think about using json schema to autogenerate (https://json-schema.org/implementations.html#documentation-generators)
- [x] This will be feature flagged and disabled by default
- [ ] Follow Project DOD

*Useful Links**

- Inspiration for the structure - https://jasonette.com/
- Inspiration for the structure - https://ui-schema.bemit.codes/
- https://www.storyblok.com/tp/react-dynamic-component-from-json
- [SPIKE](https://github.com/kyma-project/busola/issues/1222)

**Comment by majakurcius** [comment]
1. Look into the existing schemas and provided examples, solutions on the Internet and think of something that would fit our needs and decide on the final look of the JSON structure. Some work has already been done in the POC.
- menu and navigation + JSON schema docs

2.  Since we have the POC, use the stuff from the POC. Split it into different locations (Items, Details, Create).
-  list view with + json schema docs
- details view with fields for list, object and string + JSON schema docs
- create view with fields for + JSON schema docs
- excelling schema structure

3. Document the configuration with examples (or work on the autogeneration). 
- writing a README

**Comment by majakurcius** [comment]
**What's left:** 

- Agata's part is waiting to be finished: adding widgets for additional properties (Agata has no idea how to do it)
- Adding simple advanced and details to schema - half way done, maybe not even
- Adding metadata to schema
- Display components (there's a bug, the fix is being worked on, it hasn't been come up with yet)
- Documentation 
- Lists
