### ISSUE TITLE
Introduce Prometheus Graphs for Persistent Volumes Claims

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1259]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to see Prometheus Metrics regarding Persistent Volumes Claims so that I can make informed decisions about possible space allocation problems.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We use prometheus as a source for the metrics
- [x] The feature is enabled when prometheus is available in the cluster, and replaced by the current graphs when prometheus is disabled.
- [x] We will follow Fiori Guidelines when comes to the style of the graph
- [x] Our users are used to Grafana dashboards, so  when choosing a graph style use https://grafana.com/docs/grafana/latest/visualizations/ as inspiration
- [x] We show Volume Usage Limits
- [x] We use our existing dual graph to display free and used space

**Tasks**

- [ ] task 1
