### ISSUE TITLE
Remove old Service Catalog

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1595]
**Description**

Since old Service Catalog is no longer used we can remove it from Busola.

**Reasons**

No point keeping it here.

**Tasks**

- [x] Remove catalog-related views.
- [x] Remove sublists from other resource views (e.g. `ServiceBindings` on Function details)
- [x] Remove packages used by catalog
- [x] Cleanup configuration (config-overrides.js, jsconfig etc)
- [x] Adjust tests
- [x] Adjust docs (e.g. features one)
