### ISSUE TITLE
Migrate All Existing non CORE views to extensions 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1780]
**Description**

We want to keep the core of Busola Clean. We will migrate all non k8s native related views to their own extension and use the extensibility mechanism to recreate and improve the existing views.

**Related Tasks**

- [x] Technical Tasks
  - [x] https://github.com/kyma-project/busola/issues/1818 
  - [x] https://github.com/kyma-project/busola/issues/1770
- [x] Move all ISTIO views
  - [x] https://github.com/kyma-project/busola/issues/1731
  - [x] https://github.com/kyma-project/busola/issues/1730
  - [x] https://github.com/kyma-project/busola/issues/1729
  - [x] https://github.com/kyma-project/busola/issues/1732
  - [x] https://github.com/kyma-project/busola/issues/1733
  - [x] https://github.com/kyma-project/busola/issues/1734
- [ ] Move all Kyma specific views to extensions
  - [x] https://github.com/kyma-project/busola/issues/1735
  - [x] https://github.com/kyma-project/busola/issues/1728
  - [x] https://github.com/kyma-project/busola/issues/1865
  - [x] https://github.com/kyma-project/busola/issues/1866
  - [x] https://github.com/kyma-project/busola/issues/1779
  - [x] https://github.com/kyma-project/busola/issues/1958
  - [x] https://github.com/kyma-project/busola/issues/1959
  - [x] https://github.com/kyma-project/busola/issues/1960
  - [x] https://github.com/kyma-project/busola/issues/1961
  - [x] https://github.com/kyma-project/busola/issues/1957
  - [x] https://github.com/kyma-project/busola/issues/1956
  - [x] https://github.com/kyma-project/busola/issues/1955
  - [x] https://github.com/kyma-project/busola/issues/2042
