### ISSUE TITLE
Enable Login with Gardener

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1781]
**Description**

Busola has the option to login with Gardener, and import all existing Clusters.

**Reasons**

This has the potential to increase adoption for non Kyma clusters, and improve the multi cluster option in a Gardener env.

**Attachments**

- [x] https://github.com/kyma-project/busola/issues/1753
- [x] https://github.com/kyma-project/busola/issues/1819
- [x] https://github.com/kyma-project/busola/issues/1838

**Comment by mrCherry97** [comment]
Closing this epic as it is replaced by the new epic #5339, which revisits the existing (dormant) Gardener login code, validates it against the current Gardener APIs and OIDC flow, and plans the steps to bring it back to life. Please follow #5339 going forward.
