### ISSUE TITLE
Remove Luigi as dependency

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1924]
**Description**

As we moved away from using Microfrontends as extensibility, we no longer need the advantages provided by Luigi Framework

**Reasons**

Streamline our application, and speed up bootstrap time. 

**Attachments**

- [x] https://github.com/kyma-project/busola/issues/1925
- [x] https://github.com/kyma-project/busola/issues/1926
- [ ] https://github.com/kyma-project/busola/issues/1927
- [x] https://github.com/kyma-project/busola/issues/1939
- [x] https://github.com/kyma-project/busola/issues/2071
- [x] https://github.com/kyma-project/busola/issues/2077
- [x] https://github.com/kyma-project/busola/issues/2078
- [x] https://github.com/kyma-project/busola/issues/2079

**Comment by Lyczeq** [comment]
In the following [issue](https://github.com/kyma-project/busola/pull/1931) we managed to move `disableResourceProtection`, `dontConfirmDelete` and `pageSize` states to Recoil but not Theme, Language and `showHiddenNamespaces`.  The last three share state with Luigi, so if we want to deliver changes iteratively, it would be better to leave them for now and move them later.

**Comment by Lyczeq** [comment]
In the following [issue](https://github.com/kyma-project/busola/pull/1969) I've added a `version.yaml`, where the busola version is kept. We should adjust our Makefile when deleting Luigi, because currently the new busola version is set in `core/src/assets/version.yaml`.

**Comment by Lyczeq** [comment]
1a. Create store for Luigi context
&
1b. Remove cache
2. Recreate Navigation Luigi Logic in React (leave it in Luigi as it does more things there), hide the Luigi nav.
We have to move: Ext calls, `addExternalNodes`, `selfsubjectrules`, node list, destinationRules
1c. Modal with pagination and settings, feature toggles stay in Luigi
3. settings - "feature toggles" moved to React (addon to 1c)
---done
4. top nav - createNamespacesList, handlers in React to change the namespace
5.
clusterManagemnt, clusterStorage
login
Cluster handshake
kubeconfigID, behaviours like saving the last visited view, setting the current cluster when the name is present in URL
constants
feature-checks
feature-discovery (REMOVE PRIMARY, SECONDARY)
auth
6. move tracking
7. reimplenet toast (find a library)
8. remove iframe

**Comment by dariadomagala** [comment]
Luigi removal tasks (that I can think of):

- [ ] rewrite all Luigi navigates to react-router
- [ ] init requests like selfsubjectrules etc. (ideally with a loading state until we get the results)
- [ ] move all states like language etc. - remove temporary luigiMigrator
- [ ] handle events like `showMessage`, `showConfirmationModal` etc in core-ui
- [ ] cluster and extensions configuration handling (config.yaml, extensions.yaml)
- [ ] get the current namespace and cluster from the path
- [ ] login flow
- [ ] kubeconfigId
- [ ] token expiration handling
- [ ] command pallete and `/` search mechanism
- [ ] remove hooks like `useFeatures`, `useMicrofrontendContext` to use Recoil state instead
- [ ] handle errors with for example outdated or incorrect kubeconfig
- [ ] question - how react-router handles invalid links? should we add custom handling?
- [ ] Prometheus feature special handler
- [ ] use preferred storage based on the user's preferences when adding a cluster (currently we store everything in localStorage)
- [ ] after login location for the namespace-only users
- [ ] i18n
- [ ] adjust nginx, test-infra, etc.
- [ ] cleanup main package.json
- [ ] adjust tests

Strech goals:
- [ ] cache
- [ ] tracking
