### ISSUE TITLE
Introduce Pod list in the Function Detail view

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#223]
**Description**

As user I would like to be able to see the pods that are attached to a function so that I can be able to click on them and see the logs.

**Reasons**

We would like to make it easier to access the pods and also the logs for those pods.

**Tasks**

- [x] Move Env Variables to the config tab
- [x] Add the pod listing general view underneath the code editor
- [x] Improve the api calls so that we only refresh the resources that are needed for that tab view

**Comment by parostatkiem** [comment]
Possible performance problem solution: dismount inactive tabs in the `Tabs` component instead of just hiding them via CSS.

**Comment by parostatkiem** [comment]
https://github.com/kyma-project/busola/pull/232

**Comment by parostatkiem** [comment]
https://github.com/kyma-project/busola/pull/235

**Comment by parostatkiem** [comment]
https://github.com/kyma-project/busola/pull/237

**Comment by parostatkiem** [comment]
https://github.com/kyma-project/busola/pull/244
