### ISSUE TITLE
Extensions can provide widgets across multiple  parts of Busola

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2246]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to have the possibility for my extension to contextually influence certain parts of Busola and add value to our users

**Acceptance Criteria**

- [ ] Follow Project DOD
- [x] The Extension controls the injection of a fixed set of widgets in specially designated areas in Busola ( think Cluster Overview , Deployment Detail Page )
- [x] We use the same configuration for the CRD extensibility.
- [ ] Can use any widget from the detail page and JSONATA

**Useful Links**

- [example](https://example.com)

**Related Tasks**

- [x] https://github.com/kyma-project/busola/issues/1503
- [x] https://github.com/kyma-project/busola/issues/2353
- [x] https://github.com/kyma-project/busola/issues/2388

**Comment by mrCherry97** [comment]
Done threw injections.
