### ISSUE TITLE
Introduce CRD and CR views on Busola

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#226]
**Description**

As a user I would like to be able to see and edit the available CRD and CR in my cluster.

**Reasons**

**Tasks**

- [ ] CRD are visible at Cluster Overview -> Admin
- [ ] CR are visible at the namespace level Configuration -> Custom Resources
- [ ] We use the generic list and detail view, and you can edit them via the generic yaml editor
