### ISSUE TITLE
Migrate all Core Views to Extensions

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2343]
**Description**

We want to keep the core of Busola Clean. We will migrate allk8s nativ views to their own extension and use the extensibility mechanism to recreate and improve the existing views.

**Related Tasks**

- [] Technical Tasks
  - [x] https://github.com/kyma-project/busola/issues/1818 
  - [x] https://github.com/kyma-project/busola/issues/1770

- [ ] Create views for YAML only editors
  - [ ] HPA
  - [ ] Services
- [ ] Migrate the existing CORE to Extensions
  - [ ] add views here
