### ISSUE TITLE
Security and compliance validation

### ISSUE THREAD

**Issue by Akatuoro** [kyma-project/busola#2376]
**Description**

Add tooling to visualize insecure or non-compliant configurations and workloads. The validation needs to be possible for the whole cluster and can also be shown as warning when creating resources. Since security and compliance needs differ for applications, the rules need to be configurable.

**Reasons**

Keeping the Kyma runtime cluster secure and compliant is an important but sometimes not easy activity. Even if Kyma is shipping the cluster secure by default, the responsibility to keep it secure is on the user side. On application side, there may also be non-compliant or insecure configuration changes, e.g. when new features are introduced.
Validation tooling can help visualize and give a report on whether the cluster is secure and whether it complies with specific standards.

**Tasks**

- [ ] This is a core functionality that needs to have in mind performance and try not to choke the API server. 
  - [ ] We evaluate the use of javascript workers, to allow background work
  - [ ] We evaluate the use of a queue, that allows the control of requests. The concurrency will be configurable allowing for at least 2 options: aggressive/active scan or background scan
  - [ ] It's acceptable that between scans the resource can change and we don't capture that. There is no need for a watch the resource approach
  - [ ] Evaluate the possibility of using an in-memory DB that can be used as a cache and also as a source for the workers.
  - [ ] Various workers ( that can run different rulesets ) can run at different intervals.
