### ISSUE TITLE
Migrate Busola to ui5-webcomponents-react

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2540]
Migrate Busola to ui5-webcomponents-react

Small functionalities:
- [x] Badges (@mrcherry97) https://github.com/kyma-project/busola/pull/2542
- [x] Tokens (@chriskari) #2578 
- [x] Buttons (@chriskari ) #2561 
- [x] BreadCrumbs (@chriskari) #2560 
- [x] Message Strips & Notifications - (Toasts) (@chriskari) #2558 
- [x] Loader
- [x] MessageBox (@akucharska) https://github.com/kyma-project/busola/pull/2544/
- [x] Icon (@mrCherry97) https://github.com/kyma-project/busola/pull/2573
- [x] MessagePage (@chriskari) #2577 
- [x] Link (@akucharska) https://github.com/kyma-project/busola/pull/2573
- [x] Title (@mrCherry97) https://github.com/kyma-project/busola/pull/2570
- [x] BusyIndicator (@akucharska) https://github.com/kyma-project/busola/pull/2575
- [x] Switch (@chriskari ) #2582

Medium functionalities:
- [x] Dialog (@chriskari  @akucharska @mrCherry97) https://github.com/kyma-project/busola/pull/2576
- [x] Headers for list and details views  - (DynamicPageHeader DynamicPage) (@mrCherry97)  https://github.com/kyma-project/busola/pull/2569/
- [x] Tabs (@akucharska) https://github.com/kyma-project/busola/pull/2571
- [x] Top navigation (ShellBar) (@mrCherry97) https://github.com/kyma-project/busola/pull/2555
- [x] Side Navigation PR: https://github.com/kyma-project/busola/pull/2498 (@akucharska)
- [x]  Other components for extensibility

Big functionalities:
- [x] Panels (@mrCherry97) https://github.com/kyma-project/busola/pull/2570
- [x] Generic Table (@akucharska) https://github.com/kyma-project/busola/pull/2568
- [x] Forms
  - [x] Checkbox (@chriskari ) #2585
  - [x] Select (@chriskari ) #2589
  - [x] Textarea (@akucharska) https://github.com/kyma-project/busola/pull/2590
  - [x] FormInput, FormLabel, FormFieldset, InputGroup (@akucharska @mrCherry97) #2602 
  - [x] Combobox (@chriskari) #2600 
  - [x] FormRadioGroup, FormRadioItem (@chriskari) #2620
  - [x] Menu, Popover, InfoLabel (@mrCherry97) #2614 
- [x] Wizard (@mrCherry97) https://github.com/kyma-project/busola/pull/2564

No functionalities related:
- [x] Add Horizon Theme (@mrCherry97) https://github.com/kyma-project/busola/pull/2562
- [ ] Refactor of CSSes
- [x] try to stabilize cypress tests (@chriskari) #2635
- [x] remove fundamental #2630 

Bugs:
- [x] Error component? (@mrCherry97) #2644

![Image](https://github.com/kyma-project/busola/assets/46759954/9bf6112e-bc18-4e71-ac52-8d61caeb832b)

- [x] left navigation and shellbar looks broken (@akucharska) https://github.com/kyma-project/busola/pull/2643
- [x] refreshing page on namespace overview in firefox crush whole UI (@akucharska) <---- can not reproduce
- [x] font in button is broken on firefox and safari (@akucharska) https://github.com/kyma-project/busola/pull/2645

![Image](https://github.com/kyma-project/busola/assets/46759954/f270b3b1-716f-4ae8-9ddf-2c2de1d2e762)

- [x] styles for links are not working (after removing fundamental) #2631 
- [x] checkboxes are not working for extensibility (they are throwing orderedMap instead of value, check kyma resource and try to add module) (@mrCherry97) #2614
- [x] create secret form is CSS broken (@akucharska) https://github.com/kyma-project/busola/pull/2629
- [x] on Cluster overview CPU panel has additional padding #2631
- [x] on Namespace overview node graph and resources are jumping https://github.com/kyma-project/busola/pull/2643
- [x] api-rules -> create -> host value is not added after choosing kyma-gateway and value is not updated after writing something to input https://github.com/kyma-project/busola/pull/2600/files#diff-b1435b26255d78dab8023d222f46015bf5bb474dff82a21235972835956d6f32L78 maybe this causes a problem (@chriskari) #2635
- [x] yaml view in create form is too small (@chriskari) #2646
- [x] scroll in Create Extension is not working (@chriskari) #2646
- [ ] fix lighthouse job
- [x] Fix custom form validation (@chriskari) #2628
- [ ] wizard is small, buttons need to be adjusted to bottom (possibly not, we will revisit that after UX meeting)
- [x] Badges inside table are with additional blur (check after moving tables)
- [x] ExternalLink icon Is missing from sidenav (@chriskari) #2608
- [x] badges for extensibility don't have background (probably schema problems with parsing custom statuses, check APIRules for example) (@mrCherry97) #2597
- [x] MessageStrip after creating should be without an icon (`hideIcon` flag) (@chriskari) #2565
- [x] Sidebar open-close button should not be displayed on `/clusters` view (@chriskari) #2567

- [x]  implement light/dark automatically adjusting to system preferences https://github.com/kyma-project/busola/pull/2562
- [x] upload YAML button in shellbar should not be displayed on no permissions view (@chriskari) #2579
- [x] adjust mobile view: (@chriskari) #2608
- [x] styling of messageStrips is not so good (@chriskari) #2603
- [x] min-width for upload-yaml button needs to be adjusted (@chriskari) #2580 
- [x] Label for fields inside simpleList are double-rendered (@chriskari) #2603
- [x] content of the page (content on details, list view etc) should be a children of `PageHeader` component and throw as a children to `DynamicPageHeader` component
- [x] Node section on cluster details view, has empty actions (@chriskari) #2580 
- [x] Styles (@chriskari) #2603
- [x] Pod restarts should display`0` not `00` (@chriskari) #2603

Ideas:
- [ ] Sort panel should be replaced with: https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-viewsettingsdialog--docs
- [ ] use `noDataText` instead of `BodyFallback` in `GenericTable`
- [ ] In nested panels (like in Pod or Custom Resource Definition details) it would be good to have a disabled margin

![Image](https://github.com/kyma-project/busola/assets/46759954/39fe2f9d-2f62-4078-a0ed-36e98a1ccfc6)

![Image](https://github.com/kyma-project/busola/assets/46759954/cb947d77-1c84-43bf-be41-362c3acd8482)

Attachments

https://sap.github.io/ui5-webcomponents-react/?path=/docs/getting-started--docs

**Comment by mrCherry97** [comment]
https://github.com/kyma-project/busola/pull/2554/

**Comment by valentinvieriu** [comment]
Style issues on import Cluster
<img width="1687" alt="image" src="https://github.com/kyma-project/busola/assets/478866/25cd1e1d-75b1-41c1-9044-ad8c00261c93">

**Comment by valentinvieriu** [comment]
Alignment issue on Safari. See Related Resource Box

<img width="1741" alt="image" src="https://github.com/kyma-project/busola/assets/478866/1f98179a-5bde-4dde-8c76-03ce64e40538">

**Comment by valentinvieriu** [comment]
Sam Alignment on Custom Resource Definitions

<img width="2046" alt="image" src="https://github.com/kyma-project/busola/assets/478866/06ccb532-4cbd-461e-992c-1b52dc79a91f">

**Comment by valentinvieriu** [comment]
Same issue on Custom Resources - see YAML Viewer
<img width="2038" alt="image" src="https://github.com/kyma-project/busola/assets/478866/813d1ae9-c474-45ec-8365-d19177cfeeff">

**Comment by vicslavova** [comment]
Here is our review for compliance with the Product Standard UX Consistency guidelines. 
 
* The icon used everywhere for external links is the wrong one - please use “sap-icon://inspect”.
* The dialog that opens through the “+” button in the shell or the “+ Upload YAML” button in a resource page: The finalizing action in it should be “Upload”. 
* In the Events tables, the “Type” column should use the “Object Status” component (icon only variant). This would also naturally paint the info icon in a blue color.
* For the events it's also important to use the correct object status to be clear semantically - if there is an error, don't only display the event as a warning. I'm not entirely sure what's the case with the examples I can see, so take this as a general advice.
* The delete buttons in the pages should use the transparent/tertiary button style instead of the semantic.
* The delete dialog title should be in title case and the finalizing action “Delete” should use the primary button style instead of the semantic.

Two additional things that are not detrimental when it comes to being UXC compliant, but are very noticeable, so it would still be good to address them:
* There are margin issues with the page sections.
* The form factor of the UI should be changed to Compact. It is currently Cozy, which is used for mobile devices.

There are still other UX issues we noticed but we agreed that they will be addressed in the redesign.

Please message me directly on Slack or Teams if there's any need for additional clarification. Thanks!
