### ISSUE TITLE
Migrate our UI components to SAP UI 5 Webcomponents 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2583]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to see a familiar UI in all SAP Products. The look and feel and design patterns should be similar so that I don't have to learn new UI Patterns

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] All Components will be migrated to [ui5-webcomponents](https://sap.github.io/ui5-webcomponents/)
- [ ] The Main theme will be switched to Horizon Theme [horizon](https://blogs.sap.com/2022/05/24/sap-fiori-evolution-horizon-now-generally-available-in-ui-technologies-and-some-products/). Old themes will be removed.
- [ ] The functionality of the app will be similar to the existing implementation. Small adjustments are acceptable to follow the UX guidelines of Horizon.

**Useful Links**

- [ui5-webcomponents](https://sap.github.io/ui5-webcomponents/)
- [horizon](https://blogs.sap.com/2022/05/24/sap-fiori-evolution-horizon-now-generally-available-in-ui-technologies-and-some-products/)
