### ISSUE TITLE
Align Busola Design with the UX proposed improvements

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2584]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to have the best user experience when using Kyma Dashboard. 

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] Use the provided [Figma Designs](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Kyma?type=design&node-id=4978-106631&mode=design&t=ocnEWYEvu0ar7Tsu-0) as guidance and adjust the current views to follow the Designs as close as possible
- [ ] Always try to use existing components provided by [ui5-webcomponents](https://sap.github.io/ui5-webcomponents/) and develop new ones only when existing ones cannot be used
- [ ] Adjustments of the Design are acceptable but require consultation and acceptance from the UX Team
- [ ] The Rollout of the new Design will be gradual

<img width="1520" alt="image" src="https://github.com/kyma-project/busola/assets/478866/fc1beb32-5336-4862-9bbf-1a8ddb0cb445">

**Useful Links**

- [Figma Designs](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Kyma?type=design&node-id=4978-106631&mode=design&t=ocnEWYEvu0ar7Tsu-0)

**Comment by valentinvieriu** [comment]
Duplicate of https://github.com/kyma-project/busola/issues/2621
