### ISSUE TITLE
Align Busola with SAP's Horizon Visual Theme using UI5 Web Components

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2621]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Matthew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), I would like Busola to adopt the Horizon Visual Theme using UI5 Web Components. This will create a consistent and modern user experience in alignment with the SAP ecosystem.

**Acceptance Criteria**

- [x] Migrate existing UI elements in Busola to UI5 Web Components.
- [x] Update UI5 Web Components to match Horizon Theme specifications, such as rounded corners and drop shadows.
- [x] Align font sizes and weights in UI5 Web Components with Horizon Theme standards.
- [x] Implement Horizon Theme's default color palette in UI5 Web Components, ensuring high contrast.
- [x] Ensure consistent use of colors in UI5 Web Components-based custom themes as per Horizon guidelines.
- [x] Update the icon sets to be consistent with Horizon Theme in UI5 Web Components.
- [x] Update margins and padding in UI5 Web Components as per Horizon Theme specifications.
- [x] Validate all changes against the project DOD (Definition of Done).

**Useful Links**

- [SAP Horizon Theme Documentation](https://btpx.frontify.com/)
- [UI5 Web Components](https://sap.github.io/ui5-webcomponents/)
  
**Reasons**

Leveraging UI5 Web Components allows us to achieve not only visual consistency with Horizon Theme but also better alignment with SAP's technology stack. This enhances the user experience while ensuring the maintainability and future-proofing of Busola's front-end.

**Linked Items**

- [x] #2622
- [ ] #2623 

**Attachments**

- Screenshot comparing UI5 Web Components in Busola and Horizon Theme elements.
<img width="1084" alt="image" src="https://github.com/kyma-project/busola/assets/478866/28ccc031-049a-4f42-985e-f2c911a7dddb">

<img width="1082" alt="image" src="https://github.com/kyma-project/busola/assets/478866/3837b938-48bc-49df-a39e-6c6783fdb649">
