### ISSUE TITLE
Introduce 3-Steps Deep Navigation System in Busola Dashboard

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2623]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), I would like to have a 3-steps deep navigation system integrated into the Busola Dashboard so that I can navigate through the UI with better clarity, more context, and less effort.

**Acceptance Criteria**

- [x] The navigation system should follow SAP's Horizon Visual Theme.
- [x] The navigation should be implemented using UI5 Web Components.
- [x] Should consist of 3 levels: List Items -> Show Detail (on the right) -> Maximize Option.
- [x] Should offer a seamless user experience that matches the new design guidelines.
- [x] All 3 levels should be easily navigable and intuitive.
- [x] Follow Project DOD (Definition of Done).

**Useful Links**

- [UI5 Web Components](https://sap.github.io/ui5-webcomponents/)
- [SAP's Horizon Visual Theme](https://btpx.frontify.com/)
- [Figma Prototype](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7548-81549&mode=design&t=hil2eEwlt1a4UWbv-0)

**Reasons**

- **Sebastian**: As an Enterprise Architect, I value streamlined operations and modular architecture. A 3-steps deep navigation system can provide a more organized view, helping in quicker navigation, and thereby aiding in making informed tech choices.
- **Matthew**: As a Cloud-Native Engineer, I need fast and efficient ways to develop and deploy applications. An intuitive and deep navigation system directly supports my need for minimal configurations and tool flexibility.

**Attachments**

<img width="1079" alt="image" src="https://github.com/kyma-project/busola/assets/478866/e201e7dc-81c1-4730-a99e-6e92eca44883">
