### ISSUE TITLE
Redesign Kyma Modularization to Improve User Experience and Navigation

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2624]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Matthew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), we would like the Kyma Modularization feature to be redesigned based on the feedback we provided.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Integrate a hero banner on the homepage.
- [x] Add a configuration navigation node at the cluster level.
- [x] Implement card-style design for module listings based on Figma prototype.
- [x] Create dedicated landing pages for each module with additional configurations.
- [x] Utilize a 3-step navigation system for module details.
- [x] Allow in-context editing in a different tab.
- [x] Match SAP's Horizon Visual Theme.
- [x] Use UI5 Web Components.
- [x] Make sure that no modules section looks like this:
![image](https://github.com/kyma-project/busola/assets/46759954/8312228b-d466-4694-a2d7-6a207b1fd281)

- [x] https://github.com/kyma-project/busola/issues/3030
- [x] https://github.com/kyma-project/busola/issues/3031
- [x] https://github.com/kyma-project/busola/issues/3028
- [x] https://github.com/kyma-project/busola/issues/3022
- [x] https://github.com/kyma-project/busola/issues/2995

**Useful Links**

- [SAP Horizon Theme Documentation](https://btpx.frontify.com/)
- [UI5 Web Components](https://sap.github.io/ui5-webcomponents/)
- [Fima Prototype](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7548-81549&mode=design&t=hil2eEwlt1a4UWbv-0)

**Reasons**

- Enhancing the user experience based on actual user feedback ensures that the platform evolves in alignment with user needs.
- The modular landing pages provide a more organized and intuitive way for users to interact with different modules.
- A card-style design will improve readability and navigation, making it easier to access crucial information.
- The updated design and navigation features are particularly beneficial for our personas, Sebastian and Matthew, who have high standards for operational support, modular architecture, and tool flexibility.

**Attachments**

<img width="1086" alt="image" src="https://github.com/kyma-project/busola/assets/478866/0cefb4c7-a74f-46a0-8aa9-8afcdf26b521">
<img width="1086" alt="image" src="https://github.com/kyma-project/busola/assets/478866/26adc9a1-3824-45e2-a539-6fc45d3022d3">

<img width="1082" alt="image" src="https://github.com/kyma-project/busola/assets/478866/98af3dcd-f630-4f73-937c-75fb7a2d5447">
<img width="1081" alt="image" src="https://github.com/kyma-project/busola/assets/478866/7413031e-c49f-4703-aea2-beadc938386a">

**Comment by janmedrek** [comment]
As specified in [this proposal](https://github.com/kyma-project/community/issues/899) we will be introducing a separation between lifecycle and business statuses for modules. It would mean that the user needs to be presented with double status for each module - one corresponding to the overall health of the module and the workload, and a second that would indicate the module-related logic state to the user.

Some examples:
- The module was deployed and configured correctly, and everything runs fine - Healthy/Available (naming TBD) + Ready
- The module was deployed but the module operator is processing some information - Healthy/Available + Processing
- The module was deployed but there is an error in the configuration - Healthy/Available + Error
- The module deployment failed - Error (+ no status?)

We would need a way to present that in a nice way to the users, also, we would need to think on how to aggregate the "business statuses" for the modules as Kyma CR will only aggregate the lifecycle ones.

**Comment by mrCherry97** [comment]
- [x] add modules should work and edit kyma resource
   - [x] checkboxes
   - [x] dropdowns
- [x] module details should be displayed in the column layout
- [ ] when the module doesn't have a details view, custom resources should be displayed
- [ ] empty modules generic list should match figma file
- [ ] descriptions should be adjusted with TWS
- [ ] refreshing on details should work (take from params and add start column in route)

**Comment by mrCherry97** [comment]
Cards view needs to be adjusted

**Comment by mrCherry97** [comment]
Cards view needs to be adjusted

**Comment by mrCherry97** [comment]
Adjust styles on full screen and small screen (check figma)

**Comment by mrCherry97** [comment]
Sort modal will be redesign as follow up: https://github.com/kyma-project/busola/issues/2958

**Comment by mrCherry97** [comment]
Need to release kyma-dashboard

**Comment by mrCherry97** [comment]
Need adjustment for community modules and maneged.
