### ISSUE TITLE
Integrate Persistent Web-Based Kubernetes Terminal as a Kyma Module

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2782]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like the capability to manage Kubernetes clusters directly from the Kyma Dashboard via a persistent web-based terminal, delivered as a Kyma module. This module would ensure that upon installation, a new widget appears in the Kyma dashboard interface, facilitating terminal access and persisting user configurations and settings across sessions.

**Acceptance Criteria**
- [ ] The module integrates seamlessly with the Kyma Dashboard.
- [ ] User settings and configurations are persisted in a volume for future sessions.
- [ ] The terminal module is fully functional upon installation without additional setup.

**Business Value**

This feature enhances user convenience by providing a persistent, configurable terminal experience directly within the Kyma Dashboard, mirroring the functionality seen in cloud offerings like Google Cloud's terminal access.

**Reasons**

Adopting this feature simplifies the user experience and increases efficiency, especially for users familiar with CLI tools but restricted by installation permissions.

**Dependencies**

Depends on the Kyma module framework for integration and volume storage for settings persistence.

**Non-functional Requirements**
- Security and privacy must be ensured for stored user data.
- The system should maintain high availability and reliability.

**Constraints**
- Must comply with data protection and privacy laws.
- Should be designed for easy update and maintenance.

**Additional Features**
- Settings and configurations persistence across sessions.
- Instantiation of the terminal environment is managed by the module for easy access.

**Notes and Comments**

Further considerations include user experience design to ensure the terminal widget is intuitive and aligns with existing Kyma Dashboard aesthetics.

**Size or Effort**

Medium to high effort, considering the development and integration of new functionalities and persistence mechanisms.

**Mockups or Diagrams**

```mermaid
graph TD
    A[Kyma Module] -->|Instantiates| B(Pod in Kubernetes Cluster)
    A -->|Persists| C(Settings in Volume)
    B -->|Connection| D[Terminal UI]
    D -->|Persistent Connection| B
    D -->|Saves Settings| C
```
    
**Useful Links**

- [Gardener Terminal Documentation](https://github.com/gardener/dashboard/blob/master/docs/usage/using-terminal.md and )
- [Terminal Controller Manager](https://github.com/gardener/terminal-controller-manager)
  
**Attachments**

Design prototypes and user flow diagrams to be attached upon design completion.

**Comment by pbochynski** [comment]
Another option: https://github.com/cloudtty/cloudtty

**Comment by mrCherry97** [comment]
Stretch goal: https://github.com/kyma-project/busola/issues/198 - make a terminal with predefined installed packages (for example kubectl, docker, k3d)

**Comment by kwiatekus** [comment]
> Stretch goal: [#198](https://github.com/kyma-project/busola/issues/198) - make a terminal with predefined installed packages (for example kubectl, docker, k3d)

We can provide you with the base image with https://github.com/kyma-project/dev-toolbox/issues/1

**Comment by mrCherry97** [comment]
[Desings in Figma](https://www.figma.com/design/J1jLOhcjIur9Y2Ui4jYFYv/Kyma-Dashboard-Designs?node-id=17341-4101&p=f&t=fT0L6o5MgAVvcpo0-0)

**Comment by dbadura** [comment]
How it should work:

The busola create workload (pod) with dev-tools image with `container.stdin` and `container.tty` set to `true`.
When the pod is ready, the busola requests `attach` resource on created pod.
The return is the response with connection upgrade by which we can setup bi-directional stream to pod through API server.

This is how it works in `kubectl attach`.

The architecture diagram: 

<img width="704" height="890" alt="Image" src="https://github.com/user-attachments/assets/f9afe8c7-69e1-41f2-baeb-58c70e3b1635" />
