### ISSUE TITLE
Comprehensive Review and Enhancement of Kubernetes and Kyma UI Views

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2857]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Matthew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), I would like Busola to comprehensively review and enhance all native Kubernetes resources and Kyma modules. This includes ensuring adherence to design guidelines, completeness of required fields such as Resource Metadata and Status, attachment of Events, inclusion of Resource Graphs, Overview cards, and Monitoring and Health views where needed, to streamline development and operational tasks within the Kyma environment.

**Acceptance Criteria**
- [x] All native Kubernetes resources and Kyma modules are reviewed against the current design guidelines.
- [x] Each resource/module includes:
  - [x] Resource Metadata and Status fields.
  - [x] Events (if applicable).
  - [x] Resource Graph (if applicable).
  - [x] Overview cards (if applicable).
  - [x] Monitoring and Health views (if applicable).
- [x] The following Kubernetes native resources are specifically reviewed and enhanced where necessary:
 
### Kyma Resources
- [x] Check ALL Kyma Resources
  

### Workloads
- [x] Pod - https://github.com/kyma-project/busola/issues/2910
- [x] ReplicaSet - https://github.com/kyma-project/busola/issues/2909
- [x] Deployment - https://github.com/kyma-project/busola/issues/2912
- [x] StatefulSet - https://github.com/kyma-project/busola/issues/2911
- [x] DaemonSet - https://github.com/kyma-project/busola/issues/2915
- [x] Job - https://github.com/kyma-project/busola/issues/2913
- [x] CronJob - https://github.com/kyma-project/busola/issues/2914
- [x] Functions - https://github.com/kyma-project/serverless/issues/1236
- [x] Adidional clean up - https://github.com/kyma-project/busola/issues/3081

### Discovery and Network 
- [x] API Rule https://github.com/kyma-project/api-gateway/issues/1414
- [x] HPA - https://github.com/kyma-project/busola/issues/2916
- [x] Ingress - https://github.com/kyma-project/busola/issues/3067
- [x] Network Policy - https://github.com/kyma-project/busola/issues/3068
- [x] Service - https://github.com/kyma-project/busola/issues/3074

### Istio
- [x] Authorization Policy https://github.com/kyma-project/istio/issues/1096
- [x] Destination Rule https://github.com/kyma-project/istio/issues/1096
- [x] Gateway https://github.com/kyma-project/istio/issues/1096
- [x] Request Authentication https://github.com/kyma-project/istio/issues/1096
- [x] Service Entrie https://github.com/kyma-project/istio/issues/1096
- [x] Sidecar https://github.com/kyma-project/istio/issues/1096
- [x] Telemetry https://github.com/kyma-project/istio/issues/1096
- [x] Virtual Service https://github.com/kyma-project/istio/issues/1096

### Service Management
- [x] Service Binding @OliwiaGowor https://github.com/kyma-project/kyma-dashboard/pull/372
- [x] Service Instance @OliwiaGowor https://github.com/kyma-project/kyma-dashboard/pull/374

### Storage 
- [x] Persistent Volume Claim @mrCherry97 https://github.com/kyma-project/busola/pull/3319

### Apps 
- [x] Helm Release @OliwiaGowor https://github.com/kyma-project/busola/pull/3341

### Configuration
- [x] Certificate @akucharska 
- [x] Config Map @OliwiaGowor https://github.com/kyma-project/busola/pull/3300
- [x] Custom Resource @OliwiaGowor https://github.com/kyma-project/busola/pull/3346
- [x] DNS Entry @akucharska https://github.com/kyma-project/busola/issues/3326
- [x] DNS Provider @akucharska https://github.com/kyma-project/kyma-dashboard/pull/375
- [x] Issuer @chriskari https://github.com/kyma-project/kyma-dashboard/pull/366
- [x] OAuth2 Client - Depraceted resource, doesn't require any more attention 
- [x] Role Binding @mrCherry97 https://github.com/kyma-project/busola/pull/3308
- [x] Role @mrCherry97 doesn't require any enhancement 
- [x] Secret @OliwiaGowor https://github.com/kyma-project/busola/pull/3304
- [x] Service Account  @OliwiaGowor https://github.com/kyma-project/busola/pull/3301

### Cluster 
- [x] Namespace
- [x] Node  https://github.com/kyma-project/busola/issues/2817
- [x] PersistentVolume @mrCherry97 https://github.com/kyma-project/busola/issues/3208
- [x] StorageClass @mrCherry97 https://github.com/kyma-project/busola/pull/3293
- [x] Cluster Role @mrCherry97 doesn't require any enhancement 
- [x] Cluster RoleBinding @mrCherry97 https://github.com/kyma-project/busola/pull/3308
- [x] Log Pipeline https://github.com/kyma-project/telemetry-manager/issues/1576
- [x] Metric Pipeline https://github.com/kyma-project/telemetry-manager/issues/1576
- [x] Trace Pipeline https://github.com/kyma-project/telemetry-manager/issues/1576

### Namespace overview: 
- [x] Limit Range - https://github.com/kyma-project/busola/issues/2989 @OliwiaGowor 
- [x] Resource Quota - https://github.com/kyma-project/busola/issues/2991 @OliwiaGowor 

### Other: 
- [x] Events - https://github.com/kyma-project/busola/pull/3338 @chriskari

**Business Value**

- Enhances the developer and operator experience within Busola by providing a more intuitive, informative, and integrated interface.
- Reduces the learning curve for new users and accelerates the development cycle for seasoned users.
- Aligns Busola's representation of Kubernetes and Kyma resources with the best practices and standards, ensuring a reliable and high-quality user experience.

**Reasons**

- A comprehensive review and enhancement of Busola's Views will ensure that users have all necessary information and tools at their fingertips, promoting efficiency and reducing the potential for errors.

**Non-functional Requirements**

- The enhancements should be implemented without significant impacts on the performance or responsiveness of the Busola dashboard.
- All new functionalities and enhancements must be compatible with the latest versions of major browsers and follow the Fiori Guidelines.

**Dependencies**

- Coordination with the UI/UX team for design guideline updates and mockups.

**Definition of Done (DOD)**

- Code is reviewed and merged into the main branch.
- All acceptance criteria are met and functionality is verified by both product owners and UX.
- Integration tests cover all new features and are passing.

**Notes and Comments**

- Ongoing discussion and collaboration with the Kyma UX team are crucial for the success of this epic. 

**Useful Links**

- [Figma Designs](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7548-81549&mode=design&t=6Ifc5rRnGBYYl8f9-0)

**Comment by akucharska** [comment]
Checked with k8s api what is missing:

**Workloads**

-  Pod
-  ReplicaSet
-  Deployment
-  StatefulSet
-  DaemonSet
-  Job
-  CronJob

**Discovery and Network**

-  HorizontalPodAutoscaler
