### ISSUE TITLE
Move Kyma-dashboard to busola

### ISSUE THREAD

**Issue by dbadura** [kyma-project/busola#3298]
**Description**
Prepare simplification to improve release process for `busola` by unification of `kyma-dashboard` repository with `busola`. 

**Reasons**
- One release instead of two
- One `busola-web` image with different configuration instead of 4 images in total
- Bugs for kyma-dashboard can be catched at busola development instead when bumping `busola` in `kyma-dashboard`

**Execution**
- [x] Add ability to configure different `path` for configuration - https://github.com/kyma-project/busola/issues/3299
- [x] Add dockerfile to build busola with all configuration inside. Proposal: create `kyma`directory in `busola` - https://github.com/kyma-project/busola/pull/3321, https://github.com/kyma-project/busola/pull/3332
- [x] Add github actions to build new image type
- [x] Add integration tests from `kyma-dashboard` - https://github.com/kyma-project/busola/pull/3333
- [x] Allow adjusting environment in busola k8s kustomize - https://github.com/kyma-project/busola/pull/3344
- [x] Adjust environments to pickup correct environment
- [x] Add documentation https://github.com/kyma-project/busola/pull/3347, https://github.com/kyma-project/busola/pull/3402
- [x] ~~Add test to check k8s configuration~~ covered by smoke tests
- [x] Cleanup old unneeded files https://github.com/kyma-project/busola/pull/3404

**Cleanups and known issues**
- [x] When there is no yaml for specific resource, busola by default serves js and consume it. Which results in high cpu usage and many warnings, errors in console. https://github.com/kyma-project/busola/pull/3373
- [x] Unify cypress commands in tests https://github.com/kyma-project/busola/pull/3388, https://github.com/kyma-project/busola/pull/3407
**Attachments**

**Comment by dbadura** [comment]
Known issues:
- When there is no yaml for specific resource, busola by default serves `js` and consume it. Which results in high cpu usage and many warnings, errors in console.

**Comment by dbadura** [comment]
Sync of Kyma Dashboard: https://github.com/kyma-project/busola/pull/3352

**Comment by mrCherry97** [comment]
Done
