### ISSUE TITLE
Migrate ui5-webcomponents-react from v1 to v2

### ISSUE THREAD

**Issue by dbadura** [kyma-project/busola#3422]
**Description**
There is new version of `ui5-webcomponents-react` available and it looks like v1 is deprecated.
**Reasons**
We should keep our core dependencies up to date.

For example in accessiblity, we have to use refs to set `accessiblilty` props, because those props are only avaialbe in ref, for example:
[Shellbar](https://github.com/SAP/ui5-webcomponents-react/commit/f41d32b47f4ecbd818afeedb0b72a5b624e4514c#diff-2db4c472d853cc20e454d484e2b9a2ccebb4fb6f7ffadd8897c8d00e1e33e4e3R50)

The support for v1 is available till the end of the year: https://github.com/SAP/ui5-webcomponents-react?tab=readme-ov-file#ongoing-support-for-version-1x

**Attachments**
https://github.com/SAP/ui5-webcomponents-react/releases/tag/v2.0.0
https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/migration-guide--docs

**Comment by OliwiaGowor** [comment]
Things to do:
- [ ] Replace V1 Toolbar with V2 Toolbar
- [ ] Check if reset.css is still needed
- [ ] Fix popins in Tables
- [ ] Fix EmptyListComponent in Table
- [x] Tokens are now selectable and shouldn’t be
- [ ] ObjectPage and DynamicPage no longer have compatible components (headers, title, etc.) - maybe we should think about somehow splitting the code in DynamicPageComponent.js
- [ ] Toasts are not working
- [ ] The spacing is now replaced with a temporary file, we have to think how do we want to resolve it

**Comment by mrCherry97** [comment]
there is some problem of the throwing an undefined to backend (view is rendered correctly)
![Image](https://github.com/user-attachments/assets/648b5992-26da-4cc2-9618-9e2e5c4c1caf)
