### ISSUE TITLE
Kyma Companion AI Chat

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#3436]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to have Kyma Companion AI Chat in the Busola Dashboard that allows to talk with the kyma companion backend which helps to automate the process to analyze and troubleshoot a Kyma cluster by LLM (Language Model).

**Acceptance Criteria**
- [x] AI chat is easily available in the Busola Dashboard
- [x] UI is following the designs 
[Kyma Companion-compressed.pdf](https://github.com/user-attachments/files/17567819/Kyma.Companion-compressed.pdf)
- [x] The Busola Dashboard is integrated with Kyma Companion API (gh tools /kyma/ai-force/tree/main/docs/api-structure)
- [x] User could be navigated from AI Chat to the specific edit/create view of the resource to copy paste response from AI Chat

To integrate the Kyma Companion into Busola based on the POC changes, the following steps are required:

API / Backend related:
- [x] Add cluster authorization to all API requests
- [x] #3602 
- [x] #3605 
- [x] #3606 
- [x] #3772 

Frontend related:
- [x] Update UI5 components to version 2 #3600 
- [x] #3601 
- [x] #3658 
- [x] Open AI assistant from top toolbar, leave open upon resource / view changes
- [x] #3603 
- [x] #3604 
- [x] Hide behind feature flag
- [x] enhance typescript types
- [x] https://github.com/kyma-project/busola/issues/3749
- [x] https://github.com/kyma-project/busola/issues/3750

Testing:
- [x] Add unit tests https://github.com/kyma-project/busola/issues/3820
- [x] Add integration tests https://github.com/kyma-project/busola/issues/3820

**Business Value**

This feature enhances user convenience by providing an AI Chat which helps automate the process of analyzing and troubleshooting a Kyma cluster by LLM (Language Model).

**Reasons**

Adopting this feature simplifies the user experience and increases efficiency, especially for users unfamiliar with Kubernetes and Kyma.

**Dependencies**

Depends on the Kyma Companion API requirements.

**Non-functional Requirements**
- Security and privacy must be ensured for stored user data.
- The system should maintain high availability and reliability.

**Constraints**
- Must comply with data protection and privacy laws.
- Should be designed for easy update and maintenance.

**Additional Features**
- Settings and configurations persistence across sessions.
- We should be able to enable and disable this feature for different users(experimental channel, restricted markets, etc)

**Notes and Comments**

- Couple months ago, there was some PoC: https://github.com/kyma-project/busola/pull/2861

**Size or Effort**

High effort, considering the development and integration of new functionalities.

**Mockups or Diagrams**

![image](https://github.com/user-attachments/assets/2928cb70-aa49-4fed-ba76-6e579998ee83)

    
**Useful Links**

- tools/kyma/ai-force
- [Designs](https://wiki.one.int.sap/wiki/display/CPDesign/AI+Chat+Bubble)

**Comment by mrCherry97** [comment]
UX review - features: 
- [x] https://github.com/kyma-project/busola/issues/3829
- [ ] https://github.com/kyma-project/busola/issues/3869
- [ ] https://github.com/kyma-project/busola/issues/3830
- [ ] https://github.com/kyma-project/busola/issues/3831
- [ ] https://github.com/kyma-project/busola/issues/3851
- [ ] https://github.com/kyma-project/busola/issues/3833
- [ ] https://github.com/kyma-project/busola/issues/3834
- [ ] https://github.com/kyma-project/busola/issues/3835
- [ ] https://github.com/kyma-project/busola/issues/3846
- [ ] https://github.com/kyma-project/busola/issues/3836
- [ ] https://github.com/kyma-project/busola/issues/3850
- [ ] https://github.com/kyma-project/busola/issues/3852

UX review - bugs:
- [x] https://github.com/kyma-project/busola/issues/3837
- [x] https://github.com/kyma-project/busola/issues/3868
- [ ] https://github.com/kyma-project/busola/issues/3857
- [ ] https://github.com/kyma-project/busola/issues/3832

**Comment by mrCherry97** [comment]
Joule is released and pushed on PROD, so Epic could be closed.
