### ISSUE TITLE
[Kyma Dashboard] Support for updated Module Catalog

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/busola#3447]
**Description**

With the recent changes required by the [Community Modules story](https://github.com/kyma-project/kyma/issues/18450) the Module Catalog needed to be adapted. Multiple changes were introduced to the API of Kyma Lifecycle Manager, and thus, the UI logic needs to be adjusted to display them.

Along with changes, multiple quality-of-life fields were introduced that will allow Busola to share information on the modules with the Users.

**Reasons**

We want to have a streamlined, convenient experience when it comes to interacting with Kyma Modules.

**Changes**

- ModuleTemplate CRD:
  - `.spec.channel` field was deprecated
  - `.spec.info` introduced, it includes basic information on the Module that can be displayed in Busola, such as repo/docu links, icons
  - `.spec.resources` introduced, it contains a reference to all the resources that need to be installed in order for the Module to be operational (used for manual installation)
  - `spec.associatedResources` introduced, it contains a list of all module-related CRDs
  - `.spec.manager` introduced, contains a reference to the Module manager, which can be used to determine whether manually installed module is operational or not
- ModuleReleaseMeta CRD introduced
  - It contains ties between module versions and channels used  

**Acceptance Criteria**

- [x] Adjust `Add Modules` view to `.spec.channel` deprecation
https://github.com/kyma-project/busola/issues/3459
- [x] Adjust deleting the module flow with information from `.spec.associatedResources`
https://github.com/kyma-project/busola/issues/3345
- [x] Force delete for the module
https://github.com/kyma-project/busola/issues/2613
- [x] Icons for modules in the `Add Modules` view
https://github.com/kyma-project/busola/issues/3465
- [x] Information about `Beta` for modules should be taken from `ModuleReleaseMeta`
https://github.com/kyma-project/busola/issues/3519
- [x] Adjust Documentation link to .spec.info.documentation`
https://github.com/kyma-project/busola/issues/3549
- [x] Adjust Extensibility KymaCR view
https://github.com/kyma-project/busola/issues/3548

**Attachments**
- [KLM Ticket for API changes](https://github.com/kyma-project/lifecycle-manager/issues/1472)
- [ModuleTemplate CRD doc](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/contributor/resources/03-moduletemplate.md)
- [ModuleReleaseMeta CRD doc](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/contributor/resources/05-modulereleasemeta.md)

**Comment by mrCherry97** [comment]
We are waiting for the playground, after that we can plan and pick this tasks: https://github.com/kyma-project/lifecycle-manager/issues/2007
