### ISSUE TITLE
Custom busola extensions

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#3497]
**Description**
Based on the [PoC](https://github.com/kyma-project/busola/pull/3471) implement a way to load a custom extension with own UI (HTML + JS) from the config map located in the target cluster.

Acceptance criteria:
- [x] UI is loaded only when feature toggle is enabled in the cluster
- [x] proxy endpoint that allows extensions to access external resources blocked by CORS (cors proxy)
- [x] extensions should be reloaded when the cluster is changed (different cluster = different set of extensions or extensions versions)
- [x] simple example is provided that shows fetching resources from cluster and how to hit the external API
- [x] feature is documented properly 
- [x] add the point to docs how to enable that (busola-config config-map)

**Reasons**
Existing extension mechanism is too limiting.

**Attachments**
Related issues:
- https://github.com/kyma-project/busola/issues/3122
- https://github.com/kyma-project/busola/issues/3456
