### ISSUE TITLE
Integrate Kyma Companion into Busola

### ISSUE THREAD

**Issue by chriskari** [kyma-project/busola#3511]
To integrate the Kyma Companion into Busola based on the POC changes, the following steps are required:

API / Backend related:
- [ ] Add cluster authorization to all API requests
- [ ] Integrate POST `/conversations` endpoint to initialize conversations
- [ ] Integrate POST `/conversations/{conversation_id}/messages` endpoint to send and receive messages
- [ ] Handle streaming of responses
- [ ] Integrate GET `/conversations/{conversation_id}/questions` to receive follow-up questions
- [ ] Proper error handling (with meaningful message from backend)

Frontend related:
- [ ] Store session_id securely on client-side 
- [x] Open AI assistant from top toolbar, leave open upon resource / view changes
- [ ] Remove initial popup -> populate chat with welcome message and initial questions
- [ ] Remove Tabs component from chat interface
- [ ] Add AI disclaimer below input
- [ ] Add `Setup in editor` button capabilities
- [ ] block input when waiting for response using time-icon
- [ ] Update UI5 components and adjust look to match design [Kyma.Companion-compressed.pdf](https://github.com/user-attachments/files/17975075/Kyma.Companion-compressed.pdf)
- [ ] Hide behind feature flag
- [ ] adjust types

Testing:
- [ ] Add unit tests
- [ ] Add integration tests

**Comment by mrCherry97** [comment]
duplicated: https://github.com/kyma-project/busola/issues/3436
