### ISSUE TITLE
Introduce Storage Classes

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#530]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to see Storage Classes in the Busola UI.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We introduce a Storage Menu item
- [x] A List View is available
- [x] A Detail View is available
- [x] #810
- [x] Create/Edit view is available - with yaml editor only
- [x] Tests are present testing the functionality

**Tasks**

- [x] Add Tasks
