### ISSUE TITLE
Introduce Views for Virtual Services

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#535]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to see the list and the details of the VirtualServices that are in My Cluster, and also be able to create and modify existing ones

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] This is part of Istio Navigation Grouping  (Gateways are also part of the same group )
- [x] Listing View is Created. Use the fields  State | Name | Gateways | Hosts | Age - as a starting point
- [x] API Rules are deep linked with corresponding Virtual Services
- [x] Detail View is Create
- [x] Create Window is available - with yaml editor only
- [x] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
