### ISSUE TITLE
Introduce Ingress resource views

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#536]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to see the list and the details of the [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) that are in My Cluster, and also be able to create and modify existing ones

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] This is part of Discovery and Network
- [ ] Listing View is Created. Use the fields  State | Name | Target | Host| Path | Age - as a starting point
- [ ] Detail View is Create
- [ ] Create Window is available - with yaml editor only
- [ ] We support only Latest version of Ingress. We will cover the edge-cases in: https://github.com/kyma-project/busola/issues/706
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
