### ISSUE TITLE
Epic: Make the status Labels translatable

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#620]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to have a better explanation of the status LABELS in busola, and if possible those should be translatable in my language

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We cover all the status labels for our Kyma resources ( include -  DNS, Certificates, and Gateway )
- [x] We cover kubernetes default statuses
- [x] We fallback to the not translated label if there is no translation
- [x] We introduce tooltips to all statuses. The tooltips can be added on a need basis. They default to the translated label value if no tooltips are mentioned
- [x] We revisit each label and check if relevant tooltips can be extracted from the yaml file
- [x] This task contains the effort of adjusting the text and align the terminology

**Comment by valentinvieriu** [comment]
I think this is an epic. Let's close it when all the additional tasks are ready
