### ISSUE TITLE
Introduce Create Resource for any resource available in Kyma

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#653]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to create any type of resource in the Busola UI. When Form based creation is not possible, I would like to be able to use YAML format.

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We target all Resources in Busola UI that do not have a Create Resource View
- [ ] This does not apply for CRDS
- [ ] Create Window is available - with yaml editor only
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
