### ISSUE TITLE
Introduce Create Resource for any CRD

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#654]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to create any type of CR  in the Busola UI. When Form based creation is not possible, I would like to be able to use YAML format.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We target all CRDs in Busola UI that do not have a Create Resource View
- [x] We implement an universal solution that will function with any future CRD
- [x] Create Window is available - with yaml editor only
- [x] The YAML content will extract basic features from the Schema at least first level options or required fields
- [x] Tests are present testing the functionality

**Tasks**

- [x] Add Tasks
