### ISSUE TITLE
See Kyma Version in UI

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#684]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able view the Kyma version that runs in my cluster in Cluster Overview

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We introduce this as a Feature Flag 
- [x] We read the value from kyma-system namespace `reconciler.kyma-project.io/origin-version` label
- [x] We fail gracefully if user has no access to this namespace
- [x] Tests are present testing the functionality

![image](https://user-images.githubusercontent.com/478866/145190289-20a1e2b6-aa71-400f-b6c4-90a3f15bfe60.png)

**Tasks**

- [x] Add Tasks
