### ISSUE TITLE
Introduce the option to create CRDS in Busola

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#690]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to CRD  in the Busola UI.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] The feature is available at cluster level and namespace level too
- [x] Create Window is available - with yaml editor only
- [x] Tests are present testing the functionality

**Tasks**

- [x] Add Tasks
