### ISSUE TITLE
Refactor Create Event Subscription to use the New Create Resource View

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#701]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to use a familiar way to Create Event Subscription

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Create Window is available and follows the same patterns as Other Create Resource View
- [x] Same View will be used for Edit Event Subscription
- [x] Applications are autocompleted from the existing ones in the system
- [x] Help tooltips are revisited and adjusted to guide the user for a successful Event Creation
- [x] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
