### ISSUE TITLE
Introduce Events Listing and Events Detail View

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#702]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to see all the Events in my namespace and be able to modify them using the Busola UI.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Events listing and detail follow the same pattern as other List Views and Detail View
- [x] Edit mode is present in the Detail View - creating the edit view is not part of this task
- [x] TW are consulted regarding the location in the Menu
- [x] Events in Funtions will provide deep links
- [x] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
