### ISSUE TITLE
Busola Version uses hash and deep link

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#703]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to know what Busola Version I'm using. 

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Busola Version Contains the git hash from which the Busola was build. This is not the same as the Docker image hash
- [x] The git hash is deep linked with our Busola Repo
- [x] The name is changed to mention clearly that this is a Kyma Dashboard Version
- [x] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
