### ISSUE TITLE
SPIKE: Busola should be able to adapt it's Create, Edit, and Detail View depending on k8s version and Resource Version

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#706]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like that Busola automatically adapts it's UI to fitmy k8s cluster version and also be able to support older Resources versions that are created in my cluster.

**Acceptance Criteria**

- [x] Am architecture and strategy will be documented to allow Busola to adapt to different versions of K8s and CRD's
- [x] We can use Ingress resource as an example
- [x] Create, Edit and Detail View ( and List View if needed) will all the time target latest version and have a fallback for earlier versions. Fallback for Create and Edit would be YAML, and for Detail View will be a set of basic info being displayed with preview link to YAML with disclaimer.
- [x] A set of tasks will be created to apply the same strategy to the existing Busola Components

**Tasks**

- [x] Add Tasks

**Comment by Sawthis** [comment]
Estimated effort: 3 days for 2 people

**Comment by wchrapka** [comment]
We identified 3 scenarios where a version conflict may arise: 

1. kubernetes native resources -- versions are handled solely by Kubernetes, no action required.
2. CRD with designated views  --> example: gateways
- list -- add a custom column with version (custom component to display version warning)
- edition -- add a label with version to inform the user. Send the request to the previous api (override it in a hook).
- details -- display readonly yaml for previous versions  

3. CRD --> example: gateways
- list -- extract the resource list outside of the versions, show resources' version with edit/details buttons 
- details -- no action required
- edition -- add a label with version to inform the user. Send the request to the previous api (override it in a hook).


**Defining the latest API version**
The latest and default API version is taken from luigi navigation _resourceApiPath_. When we fetch a resource, we compare the _resourceApiPath_ against resource metadata.managedfield[0].apiVersion. No match means it's a different version.

**Comment by wchrapka** [comment]
The previous concept of supporting older custom resources API versions would be against the Kubernetes [versioning pattern](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/). Kubernetes allows for converting previous version CR to new ones with a webhook conversion. Let's align the concept and support only the current version of API (that is supposed to convert previous resources to the current format itself).

Suggested task -> change how custom resources are presented:
- disable edition of the non-storage versions in the Custom Resource Definitions (list and details). Add a notice that a user should modify only the storage version for compliance with storage format. This list is kept just to display information that might not be retrieved from the other endpoints.
- move the storage version to the top of the versions.
