### ISSUE TITLE
Have the option to hide fields that are not editable in YAML

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#725]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like that the YAML editors are consistent and have similar icons and functionalities 

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Introduce the icon to hide/show uneditable fields in a yaml ( managed fields, status )
- [x] Apply the change to all YAML editors ( includes edit resource )

**Tasks**

- [ ] Add Tasks
