### ISSUE TITLE
Display CRD schema in a visual way

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#726]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like that see the CRD schema in a visual way so I can use it as a documentation.

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] Replace the JSON format with a. visual solution. This solution can be external ( Apache License ) or internal.See Examples.
- [ ] Clearly mark the required fields

**Tasks**

- [ ] Add Tasks
