### ISSUE TITLE
Group CRDs by Category

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#727]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like that see the CRD grouped by their Category

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] Group CRDs in the list by [category](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories)
- [x] On CRD detail page display list to related CRDs in the same category and display the category in the header

**Tasks**

- [ ] Add Tasks

**Comment by Sawthis** [comment]
@valentinvieriu maybe better we should add the column and filter for category? If CRD has a lot of categories which category should we choose.

**Comment by Lyczeq** [comment]
There's one last thing to do. Please adjust columns width that they don't break the Scope(e.g Namespaced). `Common Custom Resource Definitions` title needs to be consulted. [Branch](https://github.com/Lyczeq/busola/tree/feature/crds-category)

**Comment by Wawrzyn321** [comment]
I have no permissions to push to @Lyczeq branch, so I've created a new one then https://github.com/kyma-project/busola/pull/760
