### ISSUE TITLE
Introduce keyboard navigation via ctr+k (⌘ k)

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#728]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to use the keyboard to navigate busola menu similar to Github using ⌘ k

![image](https://user-images.githubusercontent.com/478866/146411095-dfe570f9-553e-4d33-b5ec-8bb12d54d3aa.png)

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Introduce a ⌘ ? that will show the user the available commands
- [x] the commands will follow the `kubectl` short commands ([shortNames](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition))
- [x] This task covers basic command lines from [the SHORTNAMES list](https://kubernetes.io/docs/reference/kubectl/overview/#resource-types) and only navigates to list view
- [x] testing is performed to smoke test the feature
- [x] Absolutely great to have https://www.npmjs.com/package/didyoumean

**Examples**
- [react-command-palette](https://github.com/asabaylus/react-command-palette)
- [gitkraken](https://support.gitkraken.com/start-here/command-palette/)
- [react-super-cmd](https://saharmor.github.io/react-super-cmd/)
- [kbar](https://github.com/timc1/kbar)
- ninja-keys](https://github.com/ssleptsov/ninja-keys)
- [scoutbar](https://github.com/adenekan41/scoutbar)
**Tasks**

- [ ] Add Tasks

**Comment by Wawrzyn321** [comment]
We could use https://docs.luigi-project.io/docs/global-search/, but sadly it doesn't support "did you mean" mechanism.
