### ISSUE TITLE
Allow the control of Limit Ranges in UI

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#786]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to control Limit Ranges in the Busola UI.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We Introduce Create / Edit and Delete Button For Limit Ranges
- [ ] Create View allows only for YAML input
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
