### ISSUE TITLE
Allow control of Resource Quotas in UI

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#787]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to control Resource Quotas in the Busola UI.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We Introduce Create / Edit and Delete Button for Resource Quotas
- [ ] Create View allows only for YAML input
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
