### ISSUE TITLE
IIntroduce HPA view in U

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#788]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to control the Horizontal Pot Autoscaler in the Busola UI.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We Introduce List /Derail / Create / Edit for HPA
- [ ] Create/Edit View allows only for YAML input
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
