### ISSUE TITLE
[SPIKE] Upgrade Node, Cypress and NPM version

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#834]
**Description**

We have stopped upgrading Cypress from [9.0.0 version](https://docs.cypress.io/guides/references/changelog#9-0-0) released on 11/10/2021 where bundled Node.js version was upgraded from 14.17.0 to 16.5.0. We are still using Node 14 in Busola.

Preferably:
- upgrade Cypress to the newest version
- upgrade Node to versions 16 with Active LTS status
- upgrade npm to version 8

**Reasons**

We are missing new useful features and fixes provided in the newer versions.

**TODOs**

- [x] Use new version of Monaco - make sure it's still served locally
- [x] Bring back window titles after React router update
- [x] Bring back fonts
- [x] Check if Webpack update is actually required
- [x] Make sure everything builds in Docker and runs fine on CI
- [x] Cleanup unnecessary installed packaged and added files (like .babelrc etc)
