### ISSUE TITLE
Allow option to import all clusters in a multi context kubeconfig file

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#848]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able provide a kubeconfig file with multiple context and import them all in  Busola UI.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] There is a new option to import all contexts 
- [ ] We import all contexts without validation
- [ ] The default context is the one is active - and this one is the one we validate and use the same flow as we currently have
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
![image](https://user-images.githubusercontent.com/478866/150759469-4216ab3e-66b3-428e-bd20-c0f3df0356c7.png)
