### ISSUE TITLE
Decode Helm Chart generated secrets

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#849]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to see the contents of the Helm generated secrets in the Busola UI so that I'm aware of the content of the revisions.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We target the secrets of type `helm.sh/release.v1`
- [x] We decode the embedded informations and we display the content
- [x] When code is used we use our monaco viewer to display the changes
- [x] Tests are present testing the functionality

**Tasks**

- [x] Check  [decoding solutions](https://gist.github.com/DzeryCZ/c4adf39d4a1a99ae6e594a183628eaee)
