### ISSUE TITLE
Introduce option to edit an existing cluster in cluster overview

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#851]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able modify an existing cluster settings in Busola UI so I don't have to remove and add a new one when I need to make a change.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] An Edit menu is displayed in cluster listing
- [x] We use a Simple/Advance/Yaml editor for editing
- [x] We offer the option to change the location of the storage on top of the Simple Advance YAML ( Please use the explanation for the storage section as we have in create view )
- [x] We introduce the option to add a description for the cluster and display this in the list view
- [x] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks

**Comment by valentinvieriu** [comment]
Can you fix https://github.com/kyma-project/busola/issues/649 also in this PR?
