### ISSUE TITLE
Introduce Helm Releases Navigation at namespace Level

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#852]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to see the contents of the Helm generated secrets in the Busola UI so that I'm aware of the content of the revisions.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [x] We introduce a new menu Helm Releases
- [x] We Introduce List /Detail  ( No Create or Edit )
- [x] In the list items we display only the active ( latest ) release
- [x] In the list item we display the number of total revisions
- [x] In the Detail View we display the decoded information similar with the secrets view
- [ ] Tests are present testing the functionality

**Tasks**

- [x] Add Tasks
