### ISSUE TITLE
Allow deep Linking using kubeconfigID feature

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#853]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to introduce a deep link with kubeconfigID in Busola UI.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] After the user is logged in, we redirect the user to the deep link
- [ ] We still use ?kubeconfigID= and it will still function without deep link
- [ ] Tests are present testing the functionality

**Tasks**

- [ ]
