### ISSUE TITLE
Display and show deep links to the resources that are installed by a helm release

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#854]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to see all the resources that a helm release has generated in my cluster in Busola UI .
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] In the Detail View we display the deep link to the resources installed by the helm chart
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
