### ISSUE TITLE
Introduce name generator as a option to all Name Fields

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#874]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to have the option to generate a unique name for any resource name in Busola UI. I would also like for resources that are created in the context of other resources to have already as prefix, the name of the parent resource so that I can easy identify the owner by name.

**Acceptance Criteria**

- [x] Follow Project DOD
- [x] Align all fields to have the generate name button on the right
- [x] Remove the autogeneration from all the unnecessary resources. By default we do not generate a name
- [x] We generate a name only when the resource is created in the context of another. Example:  Events inside Functions,
- [x] Make sure we are compliant with [specs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)
- [ ] Please revisit the how fair/ correct the names in the random generation are
- [x] Tests are present testing the functionality

**Tasks**

- [ ] task 1

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/478866/150926530-38c02495-44bd-4f97-bb0f-75e2b82500d7.png">
