### ISSUE TITLE
Introduce Prometheus Metrics at Pod Level

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#901]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to see high level historical metrics like CPU utilisation, Memory and Network Usage at pod level so that I can make informed decisions about possible problematic pods.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We use prometheus as a source for the metrics
- [ ] The feature is enabled when prometheus is available in the cluster, and disabled when not - we cover the prometheus installed by Kyma but we can adapt for other installation types
- [ ] Our users are used to Grafana dashboards, so  when choosing a graph style use https://grafana.com/docs/grafana/latest/visualizations/ as inspiration
- [ ] We show CPU, Memory and Network Utilisation - with history selection of:  1h | 3h | 6h
- [ ] We use card design that is similar to the one attached
- [ ] The Refresh rate of the data is predetermined and user cannot change it - this is dependent on the history selection precision (1h | 3h | 6h)

**Tasks**

- [ ] task 1

![image](https://user-images.githubusercontent.com/478866/152782288-4533120c-4f6e-4a0b-8146-b29d11823096.png)
** Links **
- [Figma](https://www.figma.com/file/SdY41FqhOcXFJJO2DJ4meS/Prometheus-Graphs?node-id=0%3A1)
