### ISSUE TITLE
Introduce Prometheus Metrics at Cluster Level

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#927]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to see high level historical metrics like CPU utilisation, Memory and Network Usage at cluster level so that I can make informed decisions about possible resource problems.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We use prometheus as a source for the metrics
- [ ] The feature is enabled when prometheus is available in the cluster, and disabled when not 
- [ ] We will follow Fiori Guidelines when comes to the style of the graph
- [ ] Our users are used to Grafana dashboards, so  when choosing a graph style use https://grafana.com/docs/grafana/latest/visualizations/ as inspiration
- [ ] We show CPU, Memory and Network Utilisation - with history selection on lat: 1h | 3h | 6h
- [ ] We use card design that is similar to the one attached
- [ ] The Refresh rate of the data is predetermined and user cannot change it

**Tasks**

- [ ] task 1

![image](https://user-images.githubusercontent.com/478866/152782288-4533120c-4f6e-4a0b-8146-b29d11823096.png)
