### ISSUE TITLE
Introduce Prometheus Metrics regarding CPU and Memory Limits and Storage at Cluster Level

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#928]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to see Prometheus Metrics regarding CPU Limits and Requests at cluster level so that I can make informed decisions about possible resource problems.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] We use prometheus as a source for the metrics
- [x] The feature is enabled when prometheus is available in the cluster and disabled when prometheus is disabled.
- [x] We will follow Fiori Guidelines when comes to the style of the graph
- [x] Our users are used to Grafana dashboards, so  when choosing a graph style use https://grafana.com/docs/grafana/latest/visualizations/ as inspiration
- [x] We show CPU,Memory and Storage Limits and Requests
- [x] We can consider using a design that is similar to the one attached - horizontal stacked bars
- [x] This graph will be on the same level 0 separate card to Historical CPU/Memory graph on Cluster Overview
- [x] The Refresh rate of the data is predetermined and user cannot change it
- [x] Fe follow the DOD

**Tasks**

- [ ] task 1

![image](https://user-images.githubusercontent.com/478866/152783578-4b2679a8-522e-42c1-b449-45f0190b947f.png)
![image](https://user-images.githubusercontent.com/478866/152783655-562d2628-111f-4dc1-ad03-8f106fe8dbf6.png)

** External Links **
- https://learnk8s.io/setting-cpu-memory-limits-requests
- https://sysdig.com/blog/kubernetes-limits-requests/
- https://shipit.dev/posts/wasting-money-with-kubernetes.html

**Comment by majakurcius** [comment]
**Draft work plan**

1. Get the data from Grafana, to have the query (similar to other graphs)
- We need to check if we have a query that has all the information that we need, or we need to combine it, which requires more work. 
2. Find out how to display the graphs.
