### ISSUE TITLE
Introduce Sidecar View in Busola

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#946]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to control the Istio Sidecar in the Busola UI.
**Acceptance Criteria**

- [x] Follow Project DOD
- [x] The Menu is part of Istio
- [x] We Introduce List /Detail / Create / Edit for Sidecar
- [x] Create/Edit View allows only for YAML input
- [x] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
