### ISSUE TITLE
Introduce view for NetworkPolicy in Busola UI

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#948]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to be able to control the Kubernetes NetworkPolicy in the Busola UI.
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] The Menu is part of Discovery and Network
- [ ] We Introduce List /Detail / Create / Edit for NetworkPolicy
- [ ] Create/Edit View allows only for YAML input
- [ ] Tests are present testing the functionality

**Tasks**

- [ ] Add Tasks
